#!/usr/bin/env node
// Generates the typed TestForge API v2 client from the OpenAPI document served
// at /api/v2/openapi (source of truth: src/lib/openapi-v2.ts).
//
//   node scripts/generate.mjs --url http://localhost:3000
//   node scripts/generate.mjs --file ../../spec.json
//
// Emits into generated/:
//   types.d.ts   — one interface per component schema
//   client.js    — resource methods (plain ESM, no runtime deps)
//   client.d.ts  — typed signatures for those methods
//
// The output is checked in so consumers of the package never need to run this;
// re-run it whenever openapi-v2.ts changes and commit the diff.

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../generated");

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

async function loadSpec() {
  const file = arg("--file", null);
  if (file) return JSON.parse(readFileSync(resolve(process.cwd(), file), "utf8"));
  const base = arg("--url", "http://localhost:3000").replace(/\/$/, "");
  const res = await fetch(`${base}/api/v2/openapi`);
  if (!res.ok) throw new Error(`Fetching spec failed: HTTP ${res.status}`);
  return res.json();
}

// --- schema → TypeScript -------------------------------------------------

const BANNER = `// AUTO-GENERATED by scripts/generate.mjs from the TestForge OpenAPI v2 document.
// Do not edit by hand — re-run the generator instead.
`;

function refName(ref) {
  return ref.replace("#/components/schemas/", "");
}

/** Render a schema node as a TypeScript type expression. */
function tsType(schema, indent = "  ") {
  if (!schema) return "unknown";
  if (schema.$ref) return refName(schema.$ref);

  if (schema.allOf) return schema.allOf.map((s) => tsType(s, indent)).join(" & ");
  if (schema.oneOf || schema.anyOf)
    return (schema.oneOf ?? schema.anyOf).map((s) => tsType(s, indent)).join(" | ");

  // `type` may be a union array, e.g. ["string","null"].
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  const rendered = types.map((t) => {
    switch (t) {
      case "string":
        return schema.enum
          ? schema.enum.map((v) => JSON.stringify(v)).join(" | ")
          : "string";
      case "integer":
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array":
        return `${tsType(schema.items, indent)}[]`;
      case "object": {
        if (schema.additionalProperties && !schema.properties)
          return `Record<string, ${
            schema.additionalProperties === true
              ? "unknown"
              : tsType(schema.additionalProperties, indent)
          }>`;
        if (!schema.properties) return "Record<string, unknown>";
        return objectType(schema, indent);
      }
      default:
        return "unknown";
    }
  });
  // Enums already carry their own union; don't double up.
  return Array.from(new Set(rendered)).join(" | ");
}

function objectType(schema, indent) {
  const req = new Set(schema.required ?? []);
  const inner = indent + "  ";
  const lines = Object.entries(schema.properties).map(([key, prop]) => {
    const doc = prop.description ? `${inner}/** ${prop.description} */\n` : "";
    const opt = req.has(key) ? "" : "?";
    return `${doc}${inner}${JSON.stringify(key)}${opt}: ${tsType(prop, inner)};`;
  });
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function emitTypes(spec) {
  const out = [BANNER, ""];
  for (const [name, schema] of Object.entries(spec.components.schemas)) {
    if (schema.description) out.push(`/** ${schema.description} */`);
    // allOf composes cleanly as a type alias; everything else is an interface
    // so consumers can augment it.
    if (schema.allOf || schema.type !== "object" || !schema.properties)
      out.push(`export type ${name} = ${tsType(schema, "")};`, "");
    else out.push(`export interface ${name} ${objectType(schema, "")}`, "");
  }
  // The list envelope is uniform across every collection.
  out.push(
    "/** The envelope every v2 collection endpoint returns. */",
    "export interface Page<T> {",
    "  items: T[];",
    "  meta: PageMeta;",
    "}",
    ""
  );
  return out.join("\n");
}

// --- paths → client methods ----------------------------------------------

// "/projects/{slug}/milestones/{id}" → { tpl, params: ["slug","id"] }
function parsePath(p) {
  const params = [...p.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
  const tpl = p.replace(/\{(\w+)\}/g, (_, n) => `\${encodeURIComponent(${n})}`);
  return { tpl, params };
}

function methodName(op, path, verb) {
  if (op.operationId) return op.operationId;
  // Derive a stable name from the summary: "List milestones" → listMilestones.
  const words = (op.summary ?? `${verb} ${path}`)
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .split(/\s+/)
    .filter(Boolean);
  return words
    .map((w, i) =>
      i === 0
        ? w.toLowerCase()
        : w[0].toUpperCase() + w.slice(1).toLowerCase()
    )
    .join("");
}

/** The success schema for an operation, as a TS type expression. */
function responseType(op) {
  const codes = Object.keys(op.responses).filter((c) => c.startsWith("2"));
  const code = codes.find((c) => c !== "204") ?? codes[0];
  if (!code || code === "204") return "void";
  const content = op.responses[code].content?.["application/json"]?.schema;
  if (!content) return "void";
  if (content.$ref) return refName(content.$ref);
  // The list envelope: { items: Ref[], meta }.
  const itemRef = content.properties?.items?.items?.$ref;
  if (itemRef) return `Page<${refName(itemRef)}>`;
  return "unknown";
}

function requestType(op) {
  const json = op.requestBody?.content?.["application/json"]?.schema;
  if (json?.$ref) return refName(json.$ref);
  if (op.requestBody?.content?.["multipart/form-data"]) return "FormData";
  return null;
}

function collectOperations(spec) {
  const ops = [];
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [verb, op] of Object.entries(item)) {
      const { tpl, params } = parsePath(path);
      ops.push({
        name: methodName(op, path, verb),
        verb: verb.toUpperCase(),
        tpl,
        params,
        body: requestType(op),
        returns: responseType(op),
        summary: op.summary,
        query: (op.parameters ?? []).filter((p) => p.in === "query"),
        tag: (op.tags ?? ["Default"])[0],
      });
    }
  }
  return ops;
}

function emitClient(spec) {
  const ops = collectOperations(spec);
  const out = [
    BANNER,
    "// Every method returns the parsed JSON body and throws TestForgeApiError on",
    "// a non-2xx response. `request` is injected by src/index.js so auth, retries",
    "// and rate-limit bookkeeping live in one place.",
    "",
    "export function buildMethods(request) {",
    "  return {",
  ];

  for (const op of ops) {
    const args = [...op.params];
    if (op.body) args.push("body");
    args.push("options = {}");
    const sig = args.join(", ");
    const bodyArg = op.body ? "body" : "undefined";
    out.push(
      `    /** ${op.summary ?? op.name} */`,
      `    ${op.name}(${sig}) {`,
      `      return request(${JSON.stringify(op.verb)}, \`${op.tpl}\`, ${bodyArg}, options);`,
      `    },`
    );
  }

  out.push("  };", "}", "");
  return out.join("\n");
}

function emitClientTypes(spec) {
  const ops = collectOperations(spec);
  const names = Object.keys(spec.components.schemas);
  const out = [
    BANNER,
    `import type { ${names.join(", ")}, Page } from "./types.js";`,
    "",
    "export interface RequestOptions {",
    "  /** Extra query-string parameters. */",
    "  query?: Record<string, string | number | boolean | undefined>;",
    "  signal?: AbortSignal;",
    "}",
    "",
    "export interface ApiMethods {",
  ];

  for (const op of ops) {
    const args = op.params.map((p) => `${p}: string`);
    if (op.body) args.push(`body: ${op.body}`);
    args.push("options?: RequestOptions");
    out.push(
      `  /** ${op.summary ?? op.name} */`,
      `  ${op.name}(${args.join(", ")}): Promise<${op.returns}>;`
    );
  }

  out.push(
    "}",
    "",
    "export declare function buildMethods(request: unknown): ApiMethods;",
    ""
  );
  return out.join("\n");
}

// --- run -----------------------------------------------------------------

const spec = await loadSpec();
mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}/types.d.ts`, emitTypes(spec));
writeFileSync(`${outDir}/client.js`, emitClient(spec));
writeFileSync(`${outDir}/client.d.ts`, emitClientTypes(spec));

const opCount = collectOperations(spec).length;
console.log(
  `Generated ${Object.keys(spec.components.schemas).length} types and ${opCount} operations into generated/`
);
